welcome_page:
    path: /
    defaults: { _controller: MixSBundle:Default:welcome }

mix_s_homepage:
    path: /home
    defaults: { _controller: MixSBundle:Product:index}

mix_s_category_display:
    path: /categories/{catId}
    defaults: { _controller: MixSBundle:Product:displayProductsByCategory}

mix_s_product_categories_display:
    path: /categories
    defaults: { _controller: MixSBundle:Category:displayCategories }

mix_s_product_display:
    path: /product/{id}
    defaults: { _controller: MixSBundle:Product:displayProduct }

mix_s_admin_panel:
    path: /admin
    defaults: { _controller: MixSBundle:Admin/AdminPanel:index }

mix_s_admin_product:
    resource: "@MixSBundle/Resources/config/routing/product.yml"
    prefix:   /admin/product

mix_s_admin_productcategory:
    resource: "@MixSBundle/Resources/config/routing/productcategory.yml"
    prefix:   /admin/category

mix_s_admin_promotion:
    resource: "@MixSBundle/Resources/config/routing/promotion.yml"
    prefix: /admin/promotion

mix_s_admin_users_showall:
    path: /admin/users
    defaults: { _controller: MixSBundle:Admin/User:index }

mix_s_admin_user_role_change:
    path: /admin/users/changerole
    defaults: { _controller: MixSBundle:Admin/User:roleChange }

mix_s_admin_user_ban:
    path: /admin/users/ban
    defaults: { _controller: MixSBundle:Admin/User:banUser }

mix_s_admin_user_setbalance:
    path: /admin/users/setbalance
    defaults: { _controller: MixSBundle:Admin/User:setBalance }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

mix_s_cart_display:
    path: /cart
    defaults: { _controller: MixSBundle:Cart:index }

mix_s_cart_addproduct:
    path: /cart/add/{productId}
    defaults: { _controller: MixSBundle:Cart:addToCart }
    requirements:
        id: '\d+'

mix_s_cart_checkout:
    path: /cart/checkout
    defaults: { _controller: MixSBundle:Cart:checkout }

mix_s_cart_clear:
    path: /cart/clear
    defaults: { _controller: MixSBundle:Cart:clearCart }

mix_s_cart_removeproduct:
    path: /cart/remove/{productId}
    defaults: { _controller: MixSBundle:Cart:removeProductFromCart }
    requirements:
        id: '\d+'

mix_s_inventory_display:
    path: /inventory
    defaults: { _controller: MixSBundle:Inventory:index }

mix_s_inventory_sellback:
    path: /inventory/sell
    defaults: { _controller: MixSBundle:Inventory:sellBack }

mix_s_products_filtered_display:
    path: /filtered
    defaults: { _controller: MixSBundle:Product:displayProductsByFilter }

mix_s_review_new:
    path:     /product/{id}/addreview
    defaults: { _controller: MixSBundle:Review:newReviewProcess }

mix_s_admin_review_delete:
    path: /product/{id}/deletereview
    defaults: { _controller: MixSBundle:Review:deleteReviewProcess }