services:
#    mix_s.example:
#        class: Mixailoff\ShopBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    promotion_service:
        class: Mixailoff\ShopBundle\Service\PromotionService
        arguments: ['@doctrine.orm.entity_manager']