services:
#    mix_s.example:
#        class: Mixailoff\ShopBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    app.promotion.service:
        class: Mixailoff\ShopBundle\Service\PromotionService
        arguments: ['@doctrine.orm.entity_manager']

    app.cart.service:
        class: Mixailoff\ShopBundle\Service\CartService
        arguments: ['@doctrine.orm.entity_manager', '@app.promotion.service']

    app.inventory.service:
        class: Mixailoff\ShopBundle\Service\InventoryService
        arguments: ['@doctrine.orm.entity_manager', '@app.promotion.service']