<?php

namespace Mixailoff\ShopBundle\Repository;


/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllProducts()
    {
        $query = $this
            ->createQueryBuilder('p')
            ->select('p')
            ->where('p.isVisible = 1')
            ->andWhere('p.quantity != 0')
            ->OrderBy('p.createdAt', 'DESC')
            ->getQuery();

        return $query;
    }

    public function getProductsByCategory($catId)
    {
        $query = $this
            ->createQueryBuilder('p')
            ->where('p.isVisible = 1')
            ->andWhere('p.quantity != 0')
            ->andWhere('p.productcategory = ' . $catId)
            ->OrderBy('p.createdAt', 'DESC')
            ->getQuery();

        return $query;
    }

    public function getProductsByFilter($search)
    {
        $query = $this
            ->createQueryBuilder('p')
            ->where('p.isVisible = 1')
            ->andWhere('p.quantity != 0')
            ->andWhere('p.title LIKE :search')
            ->orWhere('p.description LIKE :search')
            ->setParameter('search', '%' . $search . '%')
            ->OrderBy('p.createdAt', 'DESC')
            ->getQuery()->getResult();

        return $query;
    }
}
