<?php

namespace Mixailoff\ShopBundle\Repository;

use Mixailoff\ShopBundle\Entity\ProductCategory;

/**
 * ProductCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductCategoryRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return ProductCategory[]
     */
    public function getAllProductCategories()
    {
        return $this
            ->createQueryBuilder('pc')
            ->addOrderBy('pc.name', 'ASC')
            ->getQuery()
            ->execute();
    }
}
