<?php

namespace Mixailoff\ShopBundle\Repository;

/**
 * UserInventoryProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserInventoryProductsRepository extends \Doctrine\ORM\EntityRepository
{
}
