edit_product_index:
    path:     /
    defaults: { _controller: "MixSBundle:Product:index" }
    methods:  GET

edit_product_show:
    path:     /{id}/show
    defaults: { _controller: "MixSBundle:Product:show" }
    methods:  GET

edit_product_new:
    path:     /new
    defaults: { _controller: "MixSBundle:Product:new" }
    methods:  [GET, POST]

edit_product_edit:
    path:     /{id}/edit
    defaults: { _controller: "MixSBundle:Product:edit" }
    methods:  [GET, POST]

edit_product_delete:
    path:     /{id}/delete
    defaults: { _controller: "MixSBundle:Product:delete" }
    methods:  DELETE
