admin_promotion_index:
    path:     /
    defaults: { _controller: "MixSBundle:Admin/Promotion:index" }
    methods:  GET

admin_promotion_show:
    path:     /{id}/show
    defaults: { _controller: "MixSBundle:Admin/Promotion:show" }
    methods:  GET

admin_promotion_new:
    path:     /new
    defaults: { _controller: "MixSBundle:Admin/Promotion:new" }
    methods:  [GET, POST]

admin_promotion_edit:
    path:     /{id}/edit
    defaults: { _controller: "MixSBundle:Admin/Promotion:edit" }
    methods:  [GET, POST]

admin_promotion_delete:
    path:     /{id}/delete
    defaults: { _controller: "MixSBundle:Admin/Promotion:delete" }
    methods:  DELETE
